container:
  image: node:latest

check_task:
  node_modules_cache:
    folder: testing/node_modules
    fingerprint_script: cat testing/package.json
    populate_script: cd testing && npm install
  test_script: cd testing && node test config/firefox.yaml
