container:
  image: node:latest

check_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package.json
    populate_script: npm install
  test_script: node test config/firefox.yaml
