- browser: firefox
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: '91.0'

- browser: chrome
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: '92.0'

- browser: edge
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: '92.0'

- browser: safari
  service: browserstack
  os: os x
  os_version: Big Sur
  browser_version: '14.1'

- service: browserstack
  browser: chrome
  os: windows
  os_version: '10'
  browser_version: '92.0'
  incognito: true

- browser: firefox
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: '91.0'
  incognito: true

- browser: tor browser
  path: /home/arthur/tor-browser_en-US/Browser/firefox

- browser: opera
  path: /snap/bin/opera

- browser: opera
  path: /snap/bin/opera
  incognito: true

- browser: brave
  path: /snap/bin/brave

- browser: brave
  incognito: true
  path: /snap/bin/brave

- browser: brave
  path: /snap/bin/brave
  tor_mode: true
