- browser: tor

- browser: edge

- browser: duckduckgo

- browser: firefox

- browser: chrome

- browser: opera

- browser: vivaldi

- browser: brave

- browser: samsung

- browser: yandex

- browser: mi
  disable: true

- browser: bromite
