- browser: brave
  path: /usr/bin/brave-browser-nightly
  disable: false

- browser: brave
  path: /usr/bin/brave-browser-nightly
  disable: false
  incognito: true

- browser: brave
  path: /usr/bin/brave-browser-nightly
  disable: false
  tor_mode: true

- browser: brave
  path: /snap/bin/brave
  disable: false

- browser: brave
  path: /snap/bin/brave
  disable: false
  incognito: true

- browser: brave
  path: /snap/bin/brave
  disable: false
  tor_mode: true
