- browser: brave
  path: /snap/bin/brave
  disable: false

- browser: brave
  path: /snap/bin/brave
  incognito: true
  disable: true

- browser: brave
  path: /snap/bin/brave
  tor_mode: true
  disable: true