- browser: brave
  path: /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

- browser: firefox
  path: /Applications/Firefox.app/Contents/MacOS/firefox-bin

- browser: tor browser
  path: /Applications/Tor Browser.app/Contents/MacOS/firefox

- browser: safari

- browser: chrome
  path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

- browser: edge
  path: /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
