- browser: tor
  path: /home/arthur/tor-browser_en-US/Browser/firefox

- browser: brave
  path: /snap/bin/brave

- browser: brave
  incognito: true
  path: /snap/bin/brave

- browser: brave
  path: /snap/bin/brave
  tor_mode: true

- browser: firefox
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: 'latest'

- browser: firefox
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: 'latest'
  incognito: true

- browser: chrome
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: 'latest'

- browser: chrome
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: 'latest'
  incognito: true

- browser: edge
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: 'latest'

- browser: edge
  service: browserstack
  os: windows
  os_version: '10'
  browser_version: 'latest'
  incognito: true

- browser: opera
  path: /snap/bin/opera

- browser: opera
  path: /snap/bin/opera
  incognito: true

- browser: safari
  service: browserstack
  os: os x
  os_version: Big Sur
  browser_version: 'latest'
