- browser: safari

- browser: safari
  incognito: true

- browser: firefox

- browser: firefox
  incognito: true

- browser: tor

- browser: brave

- browser: brave
  incognito: true

- browser: brave
  tor: true

- browser: chrome

- browser: chrome
  incognito: true

- browser: edge

- browser: edge
  incognito: true

- browser: opera

- browser: opera
  incognito: true

- browser: vivaldi

- browser: vivaldi
  incognito: true

