name: Lint

on:
  push:
  pull_request:

jobs:
  semistandard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Run semistandard
        run: npx --yes semistandard static/*.js live/*.js scripts/*.js
